Gen and init
dm-kulish/news_back pull request #1
Opened 2023-03-10 11:42 UTC by dm-kulish

some initial things

2023-03-13 07:01 UTC, dsulimenko commented on news_app/models.py
> +
User

2023-03-13 07:01 UTC, dsulimenko commented on news_app/models.py
> +
Tags

2023-03-13 07:04 UTC, dsulimenko commented on news_app/models.py
> +    tags = models.ManyToManyField(NewsTag, blank=True)
лучше что-то типо Post, проще будет с единственным/множественным числом потом

2023-03-13 11:18 UTC, dsulimenko commented on news_app/models.py
> +
а где class?

2023-03-13 12:26 UTC, pKotlayrov requested changes

2023-03-13 12:26 UTC, pKotlayrov commented on news_app/models.py
> +    tags = models.ManyToManyField(Tag, blank=True)
Разные модели - по разным файлам

2023-03-13 12:26 UTC, pKotlayrov commented on news_app/models.py
> +User = get_user_model()
Так же советую сразу заняться переопределением User модели и чтобы это переопределение было в первой миграции, иначе проблем не оберешься

2023-03-13 12:26 UTC, pKotlayrov commented on news_app/serializers.py
> +        fields = '__all__'
Разные сериалайзеры - по разным файлам

2023-03-13 12:26 UTC, pKotlayrov commented on news_app/views.py
> +
Ну и разные вьюхи - по разным файлам заранее

2023-03-14 10:29 UTC, pKotlayrov approved these changes

2023-03-14 11:01 UTC, dsulimenko approved these changes

2023-03-14 11:06 UTC, merged