Post create
dm-kulish/news_back pull request #4
Opened 2023-04-03 10:00 UTC by dm-kulish

2023-04-03 11:07 UTC, dsulimenko approved these changes

2023-04-04 06:40 UTC, pKotlayrov requested changes

2023-04-04 06:40 UTC, pKotlayrov commented on news_app/migrations/0009_alter_user_password.py
> +    ]
пока твои миграции не долетели до прода (в нашем случае мерж в мастер) - можно и нужно менять миграции так, чтобы была одна на фичу

2023-04-04 06:40 UTC, pKotlayrov commented on news_app/migrations/0009_alter_user_password.py
> +    ]
у django даже специальная команда есть для объединения миграций

2023-04-04 08:21 UTC, merged